import { NODE_SPAWNS, MONSTER_SPAWNS, NODE_DEFS, MONSTER_DEFS } from "../src/game/data";
import { worldCellId as cellKey } from "../src/game/world";
const n = (NODE_SPAWNS as any[]).map((s, i) => `(${i},'${cellKey(s.x, s.y)}','${s.kind}',${s.x},${s.y})`);
const m = (MONSTER_SPAWNS as any[]).map((s, i) => `(${i},'${cellKey(s.x, s.y)}','${s.kind}',${s.x},${s.y})`);
const nk = Object.entries(NODE_DEFS as any).map(([k, d]: any) => `('${k}',${d.charges ?? 3},${d.respawn},${d.time})`);
const mk = Object.entries(MONSTER_DEFS as any).map(([k, d]: any) => `('${k}',${d.hp})`);
console.log("A:", n.join(","));
console.log("B:", m.join(","));
console.log("C:", nk.join(","));
console.log("D:", mk.join(","));
