-- V5 sword release, step 2/3: stage the v5 world (inactive).
--
-- GENERATED by scripts/v5/build-migrations.mjs. Do not edit this file directly.
-- Stable spawn payload sha256: 48680a9dbd5e045d7bb4709ac64ce83e8466fd852acd091710836919a65d2743
-- 369 nodes, 361 monsters, 0 relocated from v4:
-- the sword release changes item definitions only, never world geometry.

BEGIN;

DO $v5_stage_world_guard$
BEGIN
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v5') <> 'staged' THEN
    RAISE EXCEPTION 'V5 world staging requires staged v5 content';
  END IF;
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v4' THEN
    RAISE EXCEPTION 'V5 world staging expects v4 to be the active release';
  END IF;
END
$v5_stage_world_guard$;

INSERT INTO public.game_world_spawn_sets
  (content_version, spawn_set_version, source_content_manifest_hash, spawn_hash, model_version,
   cluster_probability, world_width, world_height, movement_speed, path_cell_size,
   winter_geometry, reachability_summary)
SELECT 'v5', 'v5', 'b6945416b0e2723c9530471e7cac18edb634052931fb0aad16dcce1e294a48b4', '48680a9dbd5e045d7bb4709ac64ce83e8466fd852acd091710836919a65d2743', model_version,
       cluster_probability, world_width, world_height, movement_speed, path_cell_size,
       winter_geometry, reachability_summary
FROM public.game_world_spawn_sets
WHERE content_version = 'v4' AND spawn_set_version = 'v4'
ON CONFLICT (content_version, spawn_set_version) DO UPDATE SET
  source_content_manifest_hash = EXCLUDED.source_content_manifest_hash,
  spawn_hash = EXCLUDED.spawn_hash;

DELETE FROM public.game_world_nodes WHERE content_version = 'v5';
DELETE FROM public.game_world_monsters WHERE content_version = 'v5';
DELETE FROM public.game_content_spawns WHERE content_version = 'v5';

-- Spawn identities carry forward unchanged; only the UUID namespace input
-- changes (v4:... -> v5:...), exactly as the artifact encodes.
INSERT INTO public.game_content_spawns
  (spawn_id, content_version, spawn_set_version, entity_type, kind, ordinal, active, biome, subzone, x, y)
SELECT extensions.uuid_generate_v5(
         'bf50882c-ad8a-57ab-bb73-3ea3dd8fcb5c'::uuid,
         'v5' || ':' || entity_type || ':' || kind || ':' || ordinal),
       'v5', 'v5', entity_type, kind, ordinal, active, biome, subzone, x, y
FROM public.game_content_spawns
WHERE content_version = 'v4';

INSERT INTO public.game_world_nodes
  (spawn_id, content_version, spawn_set_version, entity_type, kind, cell, biome, subzone, x, y,
   charges, max_charges, gather_s, respawn_s)
SELECT spawn.spawn_id, 'v5', 'v5', 'node', spawn.kind, previous_world.cell, spawn.biome, spawn.subzone,
       spawn.x, spawn.y, definition.max_charges, definition.max_charges, definition.gather_s, definition.respawn_s
FROM public.game_content_spawns AS spawn
JOIN public.game_content_nodes AS definition ON definition.content_version = 'v5' AND definition.kind = spawn.kind
JOIN public.game_content_spawns AS previous ON previous.content_version = 'v4'
  AND previous.entity_type = spawn.entity_type AND previous.kind = spawn.kind AND previous.ordinal = spawn.ordinal
JOIN public.game_world_nodes AS previous_world ON previous_world.spawn_id = previous.spawn_id
WHERE spawn.content_version = 'v5' AND spawn.entity_type = 'node';

INSERT INTO public.game_world_monsters
  (spawn_id, content_version, spawn_set_version, entity_type, kind, cell, biome, subzone, x, y, hp, max_hp, respawn_s)
SELECT spawn.spawn_id, 'v5', 'v5', 'monster', spawn.kind, previous_world.cell, spawn.biome, spawn.subzone,
       spawn.x, spawn.y, definition.hp, definition.hp, definition.respawn_s
FROM public.game_content_spawns AS spawn
JOIN public.game_content_monsters AS definition ON definition.content_version = 'v5' AND definition.kind = spawn.kind
JOIN public.game_content_spawns AS previous ON previous.content_version = 'v4'
  AND previous.entity_type = spawn.entity_type AND previous.kind = spawn.kind AND previous.ordinal = spawn.ordinal
JOIN public.game_world_monsters AS previous_world ON previous_world.spawn_id = previous.spawn_id
WHERE spawn.content_version = 'v5' AND spawn.entity_type = 'monster';

DO $v5_stage_world_exit$
DECLARE
  digest text;
BEGIN
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v5') <> 730 THEN
    RAISE EXCEPTION 'V5 spawn set is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_world_nodes WHERE content_version = 'v5') <> 369 THEN
    RAISE EXCEPTION 'V5 node state is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_world_monsters WHERE content_version = 'v5') <> 361 THEN
    RAISE EXCEPTION 'V5 monster state is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v4') <> 730 THEN
    RAISE EXCEPTION 'V5 staging modified the v4 spawn set';
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || entity_type || ':' || kind || ':' || ordinal || ':' || x::float8::text
             || ':' || y::float8::text || ':' || biome || ':' || subzone, ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_content_spawns WHERE content_version = 'v5';
  IF digest <> 'b6fd2abf876adc2c1e26764a7091b7b0' THEN
    RAISE EXCEPTION 'V5 spawn rows do not match the released artifact (%)', digest;
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || kind || ':' || cell || ':' || x::float8::text || ':' || y::float8::text
             || ':' || max_charges::text || ':' || gather_s::float8::text || ':' || respawn_s::text,
           ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_world_nodes WHERE content_version = 'v5';
  IF digest <> 'e6bc42cebbe37f90886221704d6096e8' THEN
    RAISE EXCEPTION 'V5 world nodes do not match the released artifact (%)', digest;
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || kind || ':' || cell || ':' || x::float8::text || ':' || y::float8::text
             || ':' || max_hp::text || ':' || respawn_s::text, ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_world_monsters WHERE content_version = 'v5';
  IF digest <> '75df648834d4178b06e861328dd4d8d9' THEN
    RAISE EXCEPTION 'V5 world monsters do not match the released artifact (%)', digest;
  END IF;
END
$v5_stage_world_exit$;

COMMIT;