-- V5 sword release, step 3/3: atomically activate v5.
--
-- GENERATED by scripts/v5/build-migrations.mjs. Do not edit this file directly.
-- Content manifest sha256: b6945416b0e2723c9530471e7cac18edb634052931fb0aad16dcce1e294a48b4
-- Stable spawn payload sha256: 48680a9dbd5e045d7bb4709ac64ce83e8466fd852acd091710836919a65d2743
--
-- v4 keeps every content, spawn and world row and is marked 'retired',
-- so release rollback is: retire v5, re-activate v4 and repoint
-- game_content_control. Rollback does NOT restore the deleted tester weapons.
--
-- Deletion allowlist (tester-era weapon ids, owner-authorised):
--   * bronze_dagger
--   * sunspire_wand
--   * tungsten_maul
--   * wooden_club
-- Every allowlisted id is removed from equipped weapons, inventory, bank,
-- market listings and market price history. Player accounts, saves, skills, XP,
-- gold, quests, all unrelated items and all 16 swords (including their plus
-- levels) are untouched. Every save that is edited is snapshotted into
-- player_save_backups first.

BEGIN;

DO $v5_activate_guard$
DECLARE
  issues integer;
  spawn_rows integer;
  bad integer;
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v4' THEN
    RAISE EXCEPTION 'V5 activation expects v4 to be the active release';
  END IF;
  SELECT count(*) INTO issues FROM public.game_validate_content_version('v5');
  IF issues <> 0 THEN
    RAISE EXCEPTION 'V5 content failed validation with % issue(s)', issues;
  END IF;
  SELECT count(*) INTO spawn_rows FROM public.game_content_spawns WHERE content_version = 'v5';
  IF spawn_rows <> 730 THEN
    RAISE EXCEPTION 'V5 spawn set is not fully staged';
  END IF;
  IF (SELECT spawn_hash FROM public.game_world_spawn_sets WHERE content_version = 'v5' AND spawn_set_version = 'v5') <> '48680a9dbd5e045d7bb4709ac64ce83e8466fd852acd091710836919a65d2743' THEN
    RAISE EXCEPTION 'V5 spawn hash does not match the released artifact';
  END IF;
  IF (SELECT manifest_hash FROM public.game_content_versions WHERE content_version = 'v5') <> 'b6945416b0e2723c9530471e7cac18edb634052931fb0aad16dcce1e294a48b4' THEN
    RAISE EXCEPTION 'V5 manifest hash does not match the released artifact';
  END IF;

  -- The deletion ledger must name every allowlisted id, all as hard stops.
  SELECT count(*) INTO bad FROM public.game_content_migration_rules
  WHERE content_version = 'v5' AND from_id = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]) AND action = 'stop' AND to_id IS NULL;
  IF bad <> 4 THEN
    RAISE EXCEPTION 'V5 deletion ledger is incomplete (% of 4 stop rules)', bad;
  END IF;

  -- The sword ladder must be exactly the approved 16 stable ids, one per tier,
  -- each craftable and strictly stronger than the tier below it.
  IF (SELECT count(*) FROM public.game_content_items
      WHERE content_version = 'v5' AND kind = 'weapon' AND active) <> 16 THEN
    RAISE EXCEPTION 'V5 must publish exactly 16 active swords';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_items
             WHERE content_version = 'v5' AND kind = 'weapon' AND NOT (id = ANY (ARRAY['ancient_greatblade', 'ascendant_blade', 'bronze_sword', 'copper_sword', 'frost_greatblade', 'glacial_greatblade', 'iron_sword', 'mithril_blade', 'runite_greatsword', 'shadow_blade', 'starsteel_blade', 'steel_sword', 'sunsteel_blade', 'voidsteel_greatblade', 'wyrmforged_blade', 'wyrmsteel_blade']::text[]))) THEN
    RAISE EXCEPTION 'V5 publishes a weapon outside the approved stable id set';
  END IF;
  IF EXISTS (
    SELECT 1 FROM (
      SELECT attack, level_requirement, tier_index,
             lag(attack) OVER (ORDER BY tier_index) AS previous_attack,
             lag(level_requirement) OVER (ORDER BY tier_index) AS previous_level
      FROM public.game_content_items
      WHERE content_version = 'v5' AND kind = 'weapon'
    ) AS ladder
    WHERE previous_attack IS NOT NULL AND (attack <= previous_attack OR level_requirement <= previous_level)
  ) THEN
    RAISE EXCEPTION 'V5 sword progression is not monotonic';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.game_content_items AS i
    WHERE i.content_version = 'v5' AND i.kind = 'weapon'
      AND NOT EXISTS (SELECT 1 FROM public.game_content_recipes AS r
                      WHERE r.content_version = i.content_version AND r.output_item_id = i.id)
  ) THEN
    RAISE EXCEPTION 'V5 must publish a recipe for every sword';
  END IF;

  -- Content-side assertions: v5 must not define or reference a deleted id.
  IF EXISTS (SELECT 1 FROM public.game_content_items
             WHERE content_version = 'v5' AND id = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[])) THEN
    RAISE EXCEPTION 'V5 still defines a deleted weapon id';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_recipes
             WHERE content_version = 'v5' AND output_item_id = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]))
     OR EXISTS (SELECT 1 FROM public.game_content_recipe_inputs
                WHERE content_version = 'v5' AND item_id = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[])) THEN
    RAISE EXCEPTION 'A V5 recipe references a deleted weapon id';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_monster_loot
             WHERE content_version = 'v5' AND item_id = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[])) THEN
    RAISE EXCEPTION 'V5 monster loot references a deleted weapon id';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_quests AS q
             WHERE q.content_version = 'v5'
               AND (q.target_id = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[])
                    OR EXISTS (SELECT 1 FROM jsonb_array_elements(q.reward_items) AS reward
                               WHERE reward->>'item_id' = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[])))) THEN
    RAISE EXCEPTION 'A V5 quest references a deleted weapon id';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_versions AS v, unnest(ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]) AS d(id)
             WHERE v.content_version = 'v5' AND v.starter_loadout::text LIKE '%"' || d.id || '"%') THEN
    RAISE EXCEPTION 'The V5 starter loadout references a deleted weapon id';
  END IF;
END
$v5_activate_guard$;

-- ---------------------------------------------------------------------------
-- Player-side cleanup. Snapshot first, then purge.
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE v5_deleted (id text PRIMARY KEY) ON COMMIT DROP;
INSERT INTO v5_deleted (id) SELECT unnest(ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]);

CREATE TEMP TABLE v5_touched_saves ON COMMIT DROP AS
SELECT s.user_id, s.data AS before_data
FROM public.player_saves AS s
WHERE EXISTS (SELECT 1 FROM v5_deleted d WHERE s.data::text LIKE '%"' || d.id || '"%');

INSERT INTO public.player_save_backups (user_id, rev, data)
SELECT t.user_id, s.rev, t.before_data
FROM v5_touched_saves AS t
JOIN public.player_saves AS s ON s.user_id = t.user_id;

-- 1. Equipped weapon: the slot is emptied, exactly as an unequipped character.
--    Armour slots are never touched by the sword release.
UPDATE public.player_saves AS s
SET data = jsonb_set(s.data, '{weapon}', 'null'::jsonb)
WHERE s.data->'weapon'->>'id' = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]);

-- 2. Inventory slots: cleared in place, so slot count and ordering survive.
WITH cleared AS (
  SELECT s.user_id,
         jsonb_agg(CASE WHEN slot->>'id' = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]) THEN 'null'::jsonb ELSE slot END
                   ORDER BY ordinality) AS inv
  FROM public.player_saves AS s
  CROSS JOIN LATERAL jsonb_array_elements(coalesce(s.data->'inv', '[]'::jsonb)) WITH ORDINALITY AS t(slot, ordinality)
  WHERE EXISTS (
    SELECT 1 FROM jsonb_array_elements(coalesce(s.data->'inv', '[]'::jsonb)) AS probe
    WHERE probe->>'id' = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]))
  GROUP BY s.user_id
)
UPDATE public.player_saves AS s
SET data = jsonb_set(s.data, '{inv}', cleared.inv)
FROM cleared
WHERE s.user_id = cleared.user_id;

-- 3. Bank slots: same treatment.
WITH cleared AS (
  SELECT s.user_id,
         jsonb_agg(CASE WHEN slot->>'id' = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]) THEN 'null'::jsonb ELSE slot END
                   ORDER BY ordinality) AS items
  FROM public.player_saves AS s
  CROSS JOIN LATERAL jsonb_array_elements(coalesce(s.data->'bank'->'items', '[]'::jsonb)) WITH ORDINALITY AS t(slot, ordinality)
  WHERE EXISTS (
    SELECT 1 FROM jsonb_array_elements(coalesce(s.data->'bank'->'items', '[]'::jsonb)) AS probe
    WHERE probe->>'id' = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]))
  GROUP BY s.user_id
)
UPDATE public.player_saves AS s
SET data = jsonb_set(s.data, '{bank,items}', cleared.items)
FROM cleared
WHERE s.user_id = cleared.user_id;

-- 4. Market listings and price history for deleted definitions are removed.
DELETE FROM public.market_listings WHERE item_id = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]);
DELETE FROM public.market_prices WHERE item_id = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]);

-- ---------------------------------------------------------------------------
-- Activation. Only one row may hold status 'active', so v4 retires in
-- the same transaction; its content, spawn and world rows all stay in place.
-- ---------------------------------------------------------------------------
UPDATE public.game_content_versions
SET status = 'retired'
WHERE content_version = 'v4';

UPDATE public.game_content_versions
SET status = 'active'
WHERE content_version = 'v5';

UPDATE public.game_content_control
SET active_content_version = 'v5',
    active_spawn_set_version = 'v5',
    minimum_client_content_version = 'v5',
    manifest_hash = 'b6945416b0e2723c9530471e7cac18edb634052931fb0aad16dcce1e294a48b4',
    activation_timestamp = now(),
    migration_run_id = 'v5-sword-release-20260901'
WHERE singleton;

UPDATE public.game_release_control
SET minimum_client_content_version = 'v5',
    updated_at = now()
WHERE singleton;

DO $v5_activate_exit$
DECLARE
  stragglers integer;
  touched integer;
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v5' THEN
    RAISE EXCEPTION 'V5 activation did not take effect';
  END IF;
  IF (SELECT active_spawn_set_version FROM public.game_content_control WHERE singleton) <> 'v5' THEN
    RAISE EXCEPTION 'V5 spawn set activation did not take effect';
  END IF;
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v4') <> 'retired' THEN
    RAISE EXCEPTION 'v4 must be retained as retired for rollback';
  END IF;
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v4') <> 730 THEN
    RAISE EXCEPTION 'v4 rollback data was modified';
  END IF;
  IF (SELECT count(*) FROM public.game_content_items WHERE content_version = 'v4') <> 177 THEN
    RAISE EXCEPTION 'v4 rollback catalogue was modified';
  END IF;

  -- No dangling deleted ids anywhere in player-visible state.
  SELECT count(*) INTO stragglers FROM public.player_saves AS s
  WHERE EXISTS (SELECT 1 FROM v5_deleted d WHERE s.data::text LIKE '%"' || d.id || '"%');
  IF stragglers <> 0 THEN
    RAISE EXCEPTION '% save(s) still reference a deleted weapon id', stragglers;
  END IF;
  IF EXISTS (SELECT 1 FROM public.market_listings WHERE item_id = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[]))
     OR EXISTS (SELECT 1 FROM public.market_prices WHERE item_id = ANY (ARRAY['bronze_dagger', 'sunspire_wand', 'tungsten_maul', 'wooden_club']::text[])) THEN
    RAISE EXCEPTION 'The market still references a deleted weapon id';
  END IF;

  -- Every remaining item reference in every save must resolve against v5, so
  -- saves keep deserializing after the purge.
  IF EXISTS (
    SELECT 1 FROM public.player_saves AS s
    CROSS JOIN LATERAL (
      SELECT s.data->'armor'->>'id' AS id
      UNION ALL SELECT s.data->'weapon'->>'id'
      UNION ALL SELECT slot->>'id' FROM jsonb_array_elements(coalesce(s.data->'inv', '[]'::jsonb)) AS slot
      UNION ALL SELECT slot->>'id' FROM jsonb_array_elements(coalesce(s.data->'bank'->'items', '[]'::jsonb)) AS slot
    ) AS ref
    WHERE ref.id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM public.game_content_items i
                      WHERE i.content_version = 'v5' AND i.id = ref.id)
  ) THEN
    RAISE EXCEPTION 'A save references an item definition v5 does not define';
  END IF;

  -- Saves still parse into the shape the client contract expects.
  IF EXISTS (
    SELECT 1 FROM public.player_saves AS s
    WHERE jsonb_typeof(s.data->'inv') <> 'array'
       OR jsonb_typeof(s.data->'bank'->'items') <> 'array'
       OR jsonb_typeof(s.data->'skills') <> 'object'
       OR (s.data->'armor') IS NULL
       OR jsonb_typeof(s.data->'armor') NOT IN ('null', 'object')
       OR jsonb_typeof(s.data->'weapon') NOT IN ('null', 'object')
  ) THEN
    RAISE EXCEPTION 'A save no longer matches the expected save shape';
  END IF;

  IF (SELECT maintenance_mode FROM public.game_release_control WHERE singleton) THEN
    RAISE EXCEPTION 'V5 activation must not leave the game in maintenance mode';
  END IF;

  SELECT count(*) INTO touched FROM v5_touched_saves;
  RAISE NOTICE 'V5 cleanup: % save(s) purged of % deleted tester weapon id(s)', touched, 4;
END
$v5_activate_exit$;

COMMIT;
