-- V4 armour overhaul, step 3/3: atomically activate v4.
--
-- GENERATED by scripts/v4/build-migrations.mjs. Do not edit this file directly.
-- Content manifest sha256: 26e80ffe38a76677a0cbb8b768c7d06c9786c10e4717885129ef89ebd63026aa
-- Stable spawn payload sha256: 0d8a2fd6a5f83c47202e72c20536a4bc97018e0973234463d6c36a7570535faa
--
-- v3 keeps every content, spawn and world row and is marked 'retired',
-- so release rollback is: retire v4, re-activate v3 and repoint
-- game_content_control. Rollback does NOT restore the deleted tester items.
--
-- Deletion allowlist (superseded tester-era ids, owner-authorised):
--   * cloth_tunic
--   * frostguard_plate
--   * iron_mail
--   * leather_vest
--   * linen_robe
--   * mithril_plate
--   * mystic_robe
--   * runite_plate
--   * wyrmscale_plate
-- Every allowlisted id is removed from equipped gear, inventory, bank, market
-- listings and market price history. Player accounts, saves, skills, XP, gold,
-- quests and all unrelated items are untouched. Every save that is edited is
-- snapshotted into player_save_backups first.

BEGIN;

DO $v4_activate_guard$
DECLARE
  issues integer;
  spawn_rows integer;
  bad integer;
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v3' THEN
    RAISE EXCEPTION 'V4 activation expects v3 to be the active release';
  END IF;
  SELECT count(*) INTO issues FROM public.game_validate_content_version('v4');
  IF issues <> 0 THEN
    RAISE EXCEPTION 'V4 content failed validation with % issue(s)', issues;
  END IF;
  SELECT count(*) INTO spawn_rows FROM public.game_content_spawns WHERE content_version = 'v4';
  IF spawn_rows <> 730 THEN
    RAISE EXCEPTION 'V4 spawn set is not fully staged';
  END IF;
  IF (SELECT spawn_hash FROM public.game_world_spawn_sets WHERE content_version = 'v4' AND spawn_set_version = 'v4') <> '0d8a2fd6a5f83c47202e72c20536a4bc97018e0973234463d6c36a7570535faa' THEN
    RAISE EXCEPTION 'V4 spawn hash does not match the released artifact';
  END IF;
  IF (SELECT manifest_hash FROM public.game_content_versions WHERE content_version = 'v4') <> '26e80ffe38a76677a0cbb8b768c7d06c9786c10e4717885129ef89ebd63026aa' THEN
    RAISE EXCEPTION 'V4 manifest hash does not match the released artifact';
  END IF;

  -- The deletion ledger must name every allowlisted id, all as hard stops.
  SELECT count(*) INTO bad FROM public.game_content_migration_rules
  WHERE content_version = 'v4' AND from_id = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]) AND action = 'stop' AND to_id IS NULL;
  IF bad <> 9 THEN
    RAISE EXCEPTION 'V4 deletion ledger is incomplete (% of 9 stop rules)', bad;
  END IF;

  -- Content-side assertions: v4 must not define or reference a deleted id.
  IF EXISTS (SELECT 1 FROM public.game_content_items
             WHERE content_version = 'v4' AND id = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[])) THEN
    RAISE EXCEPTION 'V4 still defines a deleted item id';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_recipes
             WHERE content_version = 'v4' AND output_item_id = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]))
     OR EXISTS (SELECT 1 FROM public.game_content_recipe_inputs
                WHERE content_version = 'v4' AND item_id = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[])) THEN
    RAISE EXCEPTION 'A V4 recipe references a deleted item id';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_monster_loot
             WHERE content_version = 'v4' AND item_id = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[])) THEN
    RAISE EXCEPTION 'V4 monster loot references a deleted item id';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_quests AS q
             WHERE q.content_version = 'v4'
               AND (q.target_id = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[])
                    OR EXISTS (SELECT 1 FROM jsonb_array_elements(q.reward_items) AS reward
                               WHERE reward->>'item_id' = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[])))) THEN
    RAISE EXCEPTION 'A V4 quest references a deleted item id';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_versions AS v, unnest(ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]) AS d(id)
             WHERE v.content_version = 'v4' AND v.starter_loadout::text LIKE '%"' || d.id || '"%') THEN
    RAISE EXCEPTION 'The V4 starter loadout references a deleted item id';
  END IF;
END
$v4_activate_guard$;

-- ---------------------------------------------------------------------------
-- Player-side cleanup. Snapshot first, then purge.
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE v4_deleted (id text PRIMARY KEY) ON COMMIT DROP;
INSERT INTO v4_deleted (id) SELECT unnest(ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]);

CREATE TEMP TABLE v4_touched_saves ON COMMIT DROP AS
SELECT s.user_id, s.data AS before_data
FROM public.player_saves AS s
WHERE EXISTS (SELECT 1 FROM v4_deleted d WHERE s.data::text LIKE '%"' || d.id || '"%');

INSERT INTO public.player_save_backups (user_id, rev, data)
SELECT t.user_id, s.rev, t.before_data
FROM v4_touched_saves AS t
JOIN public.player_saves AS s ON s.user_id = t.user_id;

-- 1. Equipped gear: the slot is emptied, exactly as an unequipped character.
UPDATE public.player_saves AS s
SET data = jsonb_set(s.data, '{armor}', 'null'::jsonb)
WHERE s.data->'armor'->>'id' = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]);

UPDATE public.player_saves AS s
SET data = jsonb_set(s.data, '{weapon}', 'null'::jsonb)
WHERE s.data->'weapon'->>'id' = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]);

-- 2. Inventory slots: cleared in place, so slot count and ordering survive.
WITH cleared AS (
  SELECT s.user_id,
         jsonb_agg(CASE WHEN slot->>'id' = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]) THEN 'null'::jsonb ELSE slot END
                   ORDER BY ordinality) AS inv
  FROM public.player_saves AS s
  CROSS JOIN LATERAL jsonb_array_elements(coalesce(s.data->'inv', '[]'::jsonb)) WITH ORDINALITY AS t(slot, ordinality)
  WHERE EXISTS (
    SELECT 1 FROM jsonb_array_elements(coalesce(s.data->'inv', '[]'::jsonb)) AS probe
    WHERE probe->>'id' = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]))
  GROUP BY s.user_id
)
UPDATE public.player_saves AS s
SET data = jsonb_set(s.data, '{inv}', cleared.inv)
FROM cleared
WHERE s.user_id = cleared.user_id;

-- 3. Bank slots: same treatment.
WITH cleared AS (
  SELECT s.user_id,
         jsonb_agg(CASE WHEN slot->>'id' = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]) THEN 'null'::jsonb ELSE slot END
                   ORDER BY ordinality) AS items
  FROM public.player_saves AS s
  CROSS JOIN LATERAL jsonb_array_elements(coalesce(s.data->'bank'->'items', '[]'::jsonb)) WITH ORDINALITY AS t(slot, ordinality)
  WHERE EXISTS (
    SELECT 1 FROM jsonb_array_elements(coalesce(s.data->'bank'->'items', '[]'::jsonb)) AS probe
    WHERE probe->>'id' = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]))
  GROUP BY s.user_id
)
UPDATE public.player_saves AS s
SET data = jsonb_set(s.data, '{bank,items}', cleared.items)
FROM cleared
WHERE s.user_id = cleared.user_id;

-- 4. Market listings and price history for deleted definitions are removed.
DELETE FROM public.market_listings WHERE item_id = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]);
DELETE FROM public.market_prices WHERE item_id = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]);

-- ---------------------------------------------------------------------------
-- Activation. Only one row may hold status 'active', so v3 retires in
-- the same transaction; its content, spawn and world rows all stay in place.
-- ---------------------------------------------------------------------------
UPDATE public.game_content_versions
SET status = 'retired'
WHERE content_version = 'v3';

UPDATE public.game_content_versions
SET status = 'active'
WHERE content_version = 'v4';

UPDATE public.game_content_control
SET active_content_version = 'v4',
    active_spawn_set_version = 'v4',
    minimum_client_content_version = 'v4',
    manifest_hash = '26e80ffe38a76677a0cbb8b768c7d06c9786c10e4717885129ef89ebd63026aa',
    activation_timestamp = now(),
    migration_run_id = 'v4-armour-overhaul-20260831'
WHERE singleton;

UPDATE public.game_release_control
SET minimum_client_content_version = 'v4',
    updated_at = now()
WHERE singleton;

DO $v4_activate_exit$
DECLARE
  stragglers integer;
  touched integer;
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v4' THEN
    RAISE EXCEPTION 'V4 activation did not take effect';
  END IF;
  IF (SELECT active_spawn_set_version FROM public.game_content_control WHERE singleton) <> 'v4' THEN
    RAISE EXCEPTION 'V4 spawn set activation did not take effect';
  END IF;
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v3') <> 'retired' THEN
    RAISE EXCEPTION 'v3 must be retained as retired for rollback';
  END IF;
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v3') <> 730 THEN
    RAISE EXCEPTION 'v3 rollback data was modified';
  END IF;

  -- No dangling deleted ids anywhere in player-visible state.
  SELECT count(*) INTO stragglers FROM public.player_saves AS s
  WHERE EXISTS (SELECT 1 FROM v4_deleted d WHERE s.data::text LIKE '%"' || d.id || '"%');
  IF stragglers <> 0 THEN
    RAISE EXCEPTION '% save(s) still reference a deleted item id', stragglers;
  END IF;
  IF EXISTS (SELECT 1 FROM public.market_listings WHERE item_id = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[]))
     OR EXISTS (SELECT 1 FROM public.market_prices WHERE item_id = ANY (ARRAY['cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate']::text[])) THEN
    RAISE EXCEPTION 'The market still references a deleted item id';
  END IF;

  -- Every remaining item reference in every save must resolve against v4, so
  -- saves keep deserializing after the purge.
  IF EXISTS (
    SELECT 1 FROM public.player_saves AS s
    CROSS JOIN LATERAL (
      SELECT s.data->'armor'->>'id' AS id
      UNION ALL SELECT s.data->'weapon'->>'id'
      UNION ALL SELECT slot->>'id' FROM jsonb_array_elements(coalesce(s.data->'inv', '[]'::jsonb)) AS slot
      UNION ALL SELECT slot->>'id' FROM jsonb_array_elements(coalesce(s.data->'bank'->'items', '[]'::jsonb)) AS slot
    ) AS ref
    WHERE ref.id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM public.game_content_items i
                      WHERE i.content_version = 'v4' AND i.id = ref.id)
  ) THEN
    RAISE EXCEPTION 'A save references an item definition v4 does not define';
  END IF;

  -- Saves still parse into the shape the client contract expects.
  IF EXISTS (
    SELECT 1 FROM public.player_saves AS s
    WHERE jsonb_typeof(s.data->'inv') <> 'array'
       OR jsonb_typeof(s.data->'bank'->'items') <> 'array'
       OR jsonb_typeof(s.data->'skills') <> 'object'
       OR (s.data->'armor') IS NULL
       OR jsonb_typeof(s.data->'armor') NOT IN ('null', 'object')
       OR jsonb_typeof(s.data->'weapon') NOT IN ('null', 'object')
  ) THEN
    RAISE EXCEPTION 'A save no longer matches the expected save shape';
  END IF;

  IF (SELECT count(*) FROM public.game_content_items WHERE content_version = 'v4' AND kind = 'armor') <> 32 THEN
    RAISE EXCEPTION 'V4 must publish exactly 32 armour definitions';
  END IF;
  IF (SELECT count(*) FROM public.game_content_recipes r
      JOIN public.game_content_items i ON i.content_version = r.content_version AND i.id = r.output_item_id
      WHERE r.content_version = 'v4' AND i.kind = 'armor') <> 32 THEN
    RAISE EXCEPTION 'V4 must publish a recipe for every armour definition';
  END IF;
  IF (SELECT maintenance_mode FROM public.game_release_control WHERE singleton) THEN
    RAISE EXCEPTION 'V4 activation must not leave the game in maintenance mode';
  END IF;

  SELECT count(*) INTO touched FROM v4_touched_saves;
  RAISE NOTICE 'V4 cleanup: % save(s) purged of % deleted tester item id(s)', touched, 9;
END
$v4_activate_exit$;

COMMIT;
