-- V6 strength potion release, step 2/3: stage the v6 world (inactive).
--
-- GENERATED by scripts/v6/build-migrations.mjs. Do not edit this file directly.
-- Stable spawn payload sha256: 69a4276f9466c02eef28ff8b8d93804e9d103504c163c1e1aa630dd9aba0c163
-- 369 nodes, 361 monsters, 0 relocated from v5:
-- the potion release changes item definitions only, never world geometry.

BEGIN;

DO $v6_stage_world_guard$
BEGIN
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v6') <> 'staged' THEN
    RAISE EXCEPTION 'V6 world staging requires staged v6 content';
  END IF;
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v5' THEN
    RAISE EXCEPTION 'V6 world staging expects v5 to be the active release';
  END IF;
END
$v6_stage_world_guard$;

INSERT INTO public.game_world_spawn_sets
  (content_version, spawn_set_version, source_content_manifest_hash, spawn_hash, model_version,
   cluster_probability, world_width, world_height, movement_speed, path_cell_size,
   winter_geometry, reachability_summary)
SELECT 'v6', 'v6', 'd87267194b34a7eba300115adfa29600d1d63f52daad4e0e96b947414e673d9e', '69a4276f9466c02eef28ff8b8d93804e9d103504c163c1e1aa630dd9aba0c163', model_version,
       cluster_probability, world_width, world_height, movement_speed, path_cell_size,
       winter_geometry, reachability_summary
FROM public.game_world_spawn_sets
WHERE content_version = 'v5' AND spawn_set_version = 'v5'
ON CONFLICT (content_version, spawn_set_version) DO UPDATE SET
  source_content_manifest_hash = EXCLUDED.source_content_manifest_hash,
  spawn_hash = EXCLUDED.spawn_hash;

DELETE FROM public.game_world_nodes WHERE content_version = 'v6';
DELETE FROM public.game_world_monsters WHERE content_version = 'v6';
DELETE FROM public.game_content_spawns WHERE content_version = 'v6';

-- Spawn identities carry forward unchanged; only the UUID namespace input
-- changes (v5:... -> v6:...), exactly as the artifact encodes.
INSERT INTO public.game_content_spawns
  (spawn_id, content_version, spawn_set_version, entity_type, kind, ordinal, active, biome, subzone, x, y)
SELECT extensions.uuid_generate_v5(
         'bf50882c-ad8a-57ab-bb73-3ea3dd8fcb5c'::uuid,
         'v6' || ':' || entity_type || ':' || kind || ':' || ordinal),
       'v6', 'v6', entity_type, kind, ordinal, active, biome, subzone, x, y
FROM public.game_content_spawns
WHERE content_version = 'v5';

INSERT INTO public.game_world_nodes
  (spawn_id, content_version, spawn_set_version, entity_type, kind, cell, biome, subzone, x, y,
   charges, max_charges, gather_s, respawn_s)
SELECT spawn.spawn_id, 'v6', 'v6', 'node', spawn.kind, previous_world.cell, spawn.biome, spawn.subzone,
       spawn.x, spawn.y, definition.max_charges, definition.max_charges, definition.gather_s, definition.respawn_s
FROM public.game_content_spawns AS spawn
JOIN public.game_content_nodes AS definition ON definition.content_version = 'v6' AND definition.kind = spawn.kind
JOIN public.game_content_spawns AS previous ON previous.content_version = 'v5'
  AND previous.entity_type = spawn.entity_type AND previous.kind = spawn.kind AND previous.ordinal = spawn.ordinal
JOIN public.game_world_nodes AS previous_world ON previous_world.spawn_id = previous.spawn_id
WHERE spawn.content_version = 'v6' AND spawn.entity_type = 'node';

INSERT INTO public.game_world_monsters
  (spawn_id, content_version, spawn_set_version, entity_type, kind, cell, biome, subzone, x, y, hp, max_hp, respawn_s)
SELECT spawn.spawn_id, 'v6', 'v6', 'monster', spawn.kind, previous_world.cell, spawn.biome, spawn.subzone,
       spawn.x, spawn.y, definition.hp, definition.hp, definition.respawn_s
FROM public.game_content_spawns AS spawn
JOIN public.game_content_monsters AS definition ON definition.content_version = 'v6' AND definition.kind = spawn.kind
JOIN public.game_content_spawns AS previous ON previous.content_version = 'v5'
  AND previous.entity_type = spawn.entity_type AND previous.kind = spawn.kind AND previous.ordinal = spawn.ordinal
JOIN public.game_world_monsters AS previous_world ON previous_world.spawn_id = previous.spawn_id
WHERE spawn.content_version = 'v6' AND spawn.entity_type = 'monster';

DO $v6_stage_world_exit$
DECLARE
  digest text;
BEGIN
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v6') <> 730 THEN
    RAISE EXCEPTION 'V6 spawn set is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_world_nodes WHERE content_version = 'v6') <> 369 THEN
    RAISE EXCEPTION 'V6 node state is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_world_monsters WHERE content_version = 'v6') <> 361 THEN
    RAISE EXCEPTION 'V6 monster state is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v5') <> 730 THEN
    RAISE EXCEPTION 'V6 staging modified the v5 spawn set';
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || entity_type || ':' || kind || ':' || ordinal || ':' || x::float8::text
             || ':' || y::float8::text || ':' || biome || ':' || subzone, ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_content_spawns WHERE content_version = 'v6';
  IF digest <> '782c0631318ba203063bf6f50790f443' THEN
    RAISE EXCEPTION 'V6 spawn rows do not match the released artifact (%)', digest;
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || kind || ':' || cell || ':' || x::float8::text || ':' || y::float8::text
             || ':' || max_charges::text || ':' || gather_s::float8::text || ':' || respawn_s::text,
           ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_world_nodes WHERE content_version = 'v6';
  IF digest <> 'c1c3957ef148dcb889ae6880d199a851' THEN
    RAISE EXCEPTION 'V6 world nodes do not match the released artifact (%)', digest;
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || kind || ':' || cell || ':' || x::float8::text || ':' || y::float8::text
             || ':' || max_hp::text || ':' || respawn_s::text, ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_world_monsters WHERE content_version = 'v6';
  IF digest <> 'f0965fe221ef2ddc0baa3cf4484890ef' THEN
    RAISE EXCEPTION 'V6 world monsters do not match the released artifact (%)', digest;
  END IF;
END
$v6_stage_world_exit$;

COMMIT;