-- V3 consolidation, step 3/3: atomically activate v3.
--
-- GENERATED by scripts/v3/build-migrations.mjs. Do not edit this file directly.
-- Content manifest sha256: f8bc150f0edd4abfdec405dd7f58007d3e9da699100f2ec54cf2ecbd9fa03a0a
-- Stable spawn payload sha256: 38d2615e5ce144f70ffe8bf791603afae42b16b0c87fae1da0a1a886d7a8acba
-- v2 keeps every content, spawn and world row and is marked 'retired', so
-- rollback is: retire v3, re-activate v2 and repoint game_content_control.

BEGIN;

DO $v3_activate_guard$
DECLARE
  issues integer;
  spawn_rows integer;
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v2' THEN
    RAISE EXCEPTION 'V3 activation expects v2 to be the active release';
  END IF;
  SELECT count(*) INTO issues FROM public.game_validate_content_version('v3');
  IF issues <> 0 THEN
    RAISE EXCEPTION 'V3 content failed validation with % issue(s)', issues;
  END IF;
  SELECT count(*) INTO spawn_rows FROM public.game_content_spawns WHERE content_version = 'v3';
  IF spawn_rows <> 730 THEN
    RAISE EXCEPTION 'V3 spawn set is not fully staged';
  END IF;
  IF (SELECT spawn_hash FROM public.game_world_spawn_sets WHERE content_version = 'v3' AND spawn_set_version = 'v3') <> '38d2615e5ce144f70ffe8bf791603afae42b16b0c87fae1da0a1a886d7a8acba' THEN
    RAISE EXCEPTION 'V3 spawn hash does not match the released artifact';
  END IF;
  IF (SELECT manifest_hash FROM public.game_content_versions WHERE content_version = 'v3') <> 'f8bc150f0edd4abfdec405dd7f58007d3e9da699100f2ec54cf2ecbd9fa03a0a' THEN
    RAISE EXCEPTION 'V3 manifest hash does not match the released artifact';
  END IF;
END
$v3_activate_guard$;

-- Only one row may hold status 'active', so v2 retires in the same
-- transaction. Its content, spawn and world rows are all kept intact.
UPDATE public.game_content_versions
SET status = 'retired'
WHERE content_version = 'v2';

UPDATE public.game_content_versions
SET status = 'active'
WHERE content_version = 'v3';

UPDATE public.game_content_control
SET active_content_version = 'v3',
    active_spawn_set_version = 'v3',
    minimum_client_content_version = 'v3',
    manifest_hash = 'f8bc150f0edd4abfdec405dd7f58007d3e9da699100f2ec54cf2ecbd9fa03a0a',
    activation_timestamp = now(),
    migration_run_id = 'v3-consolidation-20260828'
WHERE singleton;

UPDATE public.game_release_control
SET minimum_client_content_version = 'v3',
    updated_at = now()
WHERE singleton;

DO $v3_activate_exit$
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v3' THEN
    RAISE EXCEPTION 'V3 activation did not take effect';
  END IF;
  IF (SELECT active_spawn_set_version FROM public.game_content_control WHERE singleton) <> 'v3' THEN
    RAISE EXCEPTION 'V3 spawn set activation did not take effect';
  END IF;
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v2') <> 'retired' THEN
    RAISE EXCEPTION 'v2 must be retained as retired for rollback';
  END IF;
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v2') <> 730 THEN
    RAISE EXCEPTION 'v2 rollback data was modified';
  END IF;
  IF (SELECT maintenance_mode FROM public.game_release_control WHERE singleton) THEN
    RAISE EXCEPTION 'V3 activation must not leave the game in maintenance mode';
  END IF;
END
$v3_activate_exit$;

COMMIT;
