-- V7 healing food release, step 2/3: stage the v7 world (inactive).
--
-- GENERATED by scripts/v7/build-migrations.mjs. Do not edit this file directly.
-- Stable spawn payload sha256: 3c3602f8247d58655d4a004f4af1cf330f606a84d0f22509e8a5ab5cdc47577c
-- 369 nodes, 361 monsters, 0 relocated from v6:
-- the healing release changes item definitions only, never world geometry.

BEGIN;

DO $v7_stage_world_guard$
BEGIN
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v7') <> 'staged' THEN
    RAISE EXCEPTION 'V7 world staging requires staged v7 content';
  END IF;
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v6' THEN
    RAISE EXCEPTION 'V7 world staging expects v6 to be the active release';
  END IF;
END
$v7_stage_world_guard$;

INSERT INTO public.game_world_spawn_sets
  (content_version, spawn_set_version, source_content_manifest_hash, spawn_hash, model_version,
   cluster_probability, world_width, world_height, movement_speed, path_cell_size,
   winter_geometry, reachability_summary)
SELECT 'v7', 'v7', '89789521c5b84948af1b954e86fdd9d6bea127d8315d3bb5b4f553d340a46935', '3c3602f8247d58655d4a004f4af1cf330f606a84d0f22509e8a5ab5cdc47577c', model_version,
       cluster_probability, world_width, world_height, movement_speed, path_cell_size,
       winter_geometry, reachability_summary
FROM public.game_world_spawn_sets
WHERE content_version = 'v6' AND spawn_set_version = 'v6'
ON CONFLICT (content_version, spawn_set_version) DO UPDATE SET
  source_content_manifest_hash = EXCLUDED.source_content_manifest_hash,
  spawn_hash = EXCLUDED.spawn_hash;

DELETE FROM public.game_world_nodes WHERE content_version = 'v7';
DELETE FROM public.game_world_monsters WHERE content_version = 'v7';
DELETE FROM public.game_content_spawns WHERE content_version = 'v7';

-- Spawn identities carry forward unchanged; only the UUID namespace input
-- changes (v6:... -> v7:...), exactly as the artifact encodes.
INSERT INTO public.game_content_spawns
  (spawn_id, content_version, spawn_set_version, entity_type, kind, ordinal, active, biome, subzone, x, y)
SELECT extensions.uuid_generate_v5(
         'bf50882c-ad8a-57ab-bb73-3ea3dd8fcb5c'::uuid,
         'v7' || ':' || entity_type || ':' || kind || ':' || ordinal),
       'v7', 'v7', entity_type, kind, ordinal, active, biome, subzone, x, y
FROM public.game_content_spawns
WHERE content_version = 'v6';

INSERT INTO public.game_world_nodes
  (spawn_id, content_version, spawn_set_version, entity_type, kind, cell, biome, subzone, x, y,
   charges, max_charges, gather_s, respawn_s)
SELECT spawn.spawn_id, 'v7', 'v7', 'node', spawn.kind, previous_world.cell, spawn.biome, spawn.subzone,
       spawn.x, spawn.y, definition.max_charges, definition.max_charges, definition.gather_s, definition.respawn_s
FROM public.game_content_spawns AS spawn
JOIN public.game_content_nodes AS definition ON definition.content_version = 'v7' AND definition.kind = spawn.kind
JOIN public.game_content_spawns AS previous ON previous.content_version = 'v6'
  AND previous.entity_type = spawn.entity_type AND previous.kind = spawn.kind AND previous.ordinal = spawn.ordinal
JOIN public.game_world_nodes AS previous_world ON previous_world.spawn_id = previous.spawn_id
WHERE spawn.content_version = 'v7' AND spawn.entity_type = 'node';

INSERT INTO public.game_world_monsters
  (spawn_id, content_version, spawn_set_version, entity_type, kind, cell, biome, subzone, x, y, hp, max_hp, respawn_s)
SELECT spawn.spawn_id, 'v7', 'v7', 'monster', spawn.kind, previous_world.cell, spawn.biome, spawn.subzone,
       spawn.x, spawn.y, definition.hp, definition.hp, definition.respawn_s
FROM public.game_content_spawns AS spawn
JOIN public.game_content_monsters AS definition ON definition.content_version = 'v7' AND definition.kind = spawn.kind
JOIN public.game_content_spawns AS previous ON previous.content_version = 'v6'
  AND previous.entity_type = spawn.entity_type AND previous.kind = spawn.kind AND previous.ordinal = spawn.ordinal
JOIN public.game_world_monsters AS previous_world ON previous_world.spawn_id = previous.spawn_id
WHERE spawn.content_version = 'v7' AND spawn.entity_type = 'monster';

DO $v7_stage_world_exit$
DECLARE
  digest text;
BEGIN
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v7') <> 730 THEN
    RAISE EXCEPTION 'V7 spawn set is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_world_nodes WHERE content_version = 'v7') <> 369 THEN
    RAISE EXCEPTION 'V7 node state is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_world_monsters WHERE content_version = 'v7') <> 361 THEN
    RAISE EXCEPTION 'V7 monster state is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v6') <> 730 THEN
    RAISE EXCEPTION 'V7 staging modified the v6 spawn set';
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || entity_type || ':' || kind || ':' || ordinal || ':' || x::float8::text
             || ':' || y::float8::text || ':' || biome || ':' || subzone, ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_content_spawns WHERE content_version = 'v7';
  IF digest <> '8f98a2d40a09a62461f642089406eebc' THEN
    RAISE EXCEPTION 'V7 spawn rows do not match the released artifact (%)', digest;
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || kind || ':' || cell || ':' || x::float8::text || ':' || y::float8::text
             || ':' || max_charges::text || ':' || gather_s::float8::text || ':' || respawn_s::text,
           ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_world_nodes WHERE content_version = 'v7';
  IF digest <> '5a6a9448310d2a01b3a27648a92cf5ef' THEN
    RAISE EXCEPTION 'V7 world nodes do not match the released artifact (%)', digest;
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || kind || ':' || cell || ':' || x::float8::text || ':' || y::float8::text
             || ':' || max_hp::text || ':' || respawn_s::text, ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_world_monsters WHERE content_version = 'v7';
  IF digest <> '90733f00ffd563a7e06ee54476e7e7f3' THEN
    RAISE EXCEPTION 'V7 world monsters do not match the released artifact (%)', digest;
  END IF;
END
$v7_stage_world_exit$;

COMMIT;