-- V4 armour overhaul, step 3/3: atomically activate v4.
--
-- GENERATED by scripts/v4/build-migrations.mjs. Do not edit this file directly.
-- Content manifest sha256: 9608c4031c2bed1b9335802b2328e8b90d7866b5d23110c7d3157fa2f50ebf41
-- Stable spawn payload sha256: 67b857de15eb32a8305595f5320fd2b6009e7d6de8bc40c2d53c790a898610cb
--
-- v3 keeps every content, spawn and world row and is marked 'retired',
-- so rollback is: retire v4, re-activate v3, repoint
-- game_content_control, and invert the enumerated player carry-over below.
--
-- Player carry-over. Nine off-theme armour definitions retire in this release.
-- Each has a canonical same-tier, same-family successor, so:
--   * an equipped copy becomes its successor at the same upgrade level
--   * a loose copy (inventory or bank) pays captured cutover unit value in gold
--   * an open market listing is relisted as the successor at the same price
-- Every touched save is snapshotted into player_save_backups first, and the
-- save revision is left alone so live clients reconcile normally.

BEGIN;

DO $v4_activate_guard$
DECLARE
  issues integer;
  spawn_rows integer;
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v3' THEN
    RAISE EXCEPTION 'V4 activation expects v3 to be the active release';
  END IF;
  SELECT count(*) INTO issues FROM public.game_validate_content_version('v4');
  IF issues <> 0 THEN
    RAISE EXCEPTION 'V4 content failed validation with % issue(s)', issues;
  END IF;
  SELECT count(*) INTO spawn_rows FROM public.game_content_spawns WHERE content_version = 'v4';
  IF spawn_rows <> 730 THEN
    RAISE EXCEPTION 'V4 spawn set is not fully staged';
  END IF;
  IF (SELECT spawn_hash FROM public.game_world_spawn_sets WHERE content_version = 'v4' AND spawn_set_version = 'v4') <> '67b857de15eb32a8305595f5320fd2b6009e7d6de8bc40c2d53c790a898610cb' THEN
    RAISE EXCEPTION 'V4 spawn hash does not match the released artifact';
  END IF;
  IF (SELECT manifest_hash FROM public.game_content_versions WHERE content_version = 'v4') <> '9608c4031c2bed1b9335802b2328e8b90d7866b5d23110c7d3157fa2f50ebf41' THEN
    RAISE EXCEPTION 'V4 manifest hash does not match the released artifact';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.game_content_migration_rules
    WHERE content_version = 'v4' AND from_id IN ('cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate')
    GROUP BY content_version HAVING count(*) <> 9
  ) OR NOT EXISTS (
    SELECT 1 FROM public.game_content_migration_rules
    WHERE content_version = 'v4' AND from_id IN ('cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate')
  ) THEN
    RAISE EXCEPTION 'V4 retirement ledger is incomplete';
  END IF;
END
$v4_activate_guard$;

-- Captured cutover unit values, read from the release being replaced.
CREATE TEMP TABLE v4_retirement ON COMMIT DROP AS
SELECT rule.from_id,
       rule.to_id,
       previous_item.value AS captured_value
FROM public.game_content_migration_rules AS rule
JOIN public.game_content_items AS previous_item
  ON previous_item.content_version = 'v3' AND previous_item.id = rule.from_id
WHERE rule.content_version = 'v4' AND rule.from_id IN ('cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate');

CREATE TEMP TABLE v4_touched_saves ON COMMIT DROP AS
SELECT s.user_id, s.data AS before_data
FROM public.player_saves AS s
WHERE EXISTS (SELECT 1 FROM v4_retirement r WHERE s.data::text LIKE '%"' || r.from_id || '"%');

INSERT INTO public.player_save_backups (user_id, rev, data)
SELECT t.user_id, s.rev, t.before_data
FROM v4_touched_saves AS t
JOIN public.player_saves AS s ON s.user_id = t.user_id;

-- 1. Equipped armour becomes its successor, upgrade level preserved.
UPDATE public.player_saves AS s
SET data = jsonb_set(s.data, '{armor,id}', to_jsonb(
      CASE s.data->'armor'->>'id'
      WHEN 'cloth_tunic' THEN 'copper_light_armor'
      WHEN 'frostguard_plate' THEN 'starsteel_heavy_armor'
      WHEN 'iron_mail' THEN 'steel_heavy_armor'
      WHEN 'leather_vest' THEN 'bronze_light_armor'
      WHEN 'linen_robe' THEN 'iron_light_armor'
      WHEN 'mithril_plate' THEN 'sunsteel_heavy_armor'
      WHEN 'mystic_robe' THEN 'shadowsteel_light_armor'
      WHEN 'runite_plate' THEN 'froststeel_heavy_armor'
      WHEN 'wyrmscale_plate' THEN 'voidsteel_heavy_armor'
      END))
WHERE s.data->'armor'->>'id' IN ('cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate');

-- 2. Loose copies (inventory slots and bank slots) pay captured value in gold
--    and are cleared, so no save can reference a definition v4 does not have.
WITH loose AS (
  SELECT s.user_id,
         coalesce(sum(coalesce((slot->>'qty')::int, 1) * r.captured_value), 0) AS refund
  FROM public.player_saves AS s
  CROSS JOIN LATERAL jsonb_array_elements(coalesce(s.data->'inv', '[]'::jsonb)) AS slot
  JOIN v4_retirement AS r ON r.from_id = slot->>'id'
  GROUP BY s.user_id
), cleared AS (
  SELECT s.user_id,
         jsonb_agg(CASE WHEN slot->>'id' IN ('cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate') THEN 'null'::jsonb ELSE slot END
                   ORDER BY ordinality) AS inv
  FROM public.player_saves AS s
  CROSS JOIN LATERAL jsonb_array_elements(coalesce(s.data->'inv', '[]'::jsonb)) WITH ORDINALITY AS t(slot, ordinality)
  WHERE s.user_id IN (SELECT user_id FROM loose)
  GROUP BY s.user_id
)
UPDATE public.player_saves AS s
SET data = jsonb_set(
      jsonb_set(s.data, '{inv}', cleared.inv),
      '{gold}',
      to_jsonb(coalesce((s.data->>'gold')::bigint, 0) + loose.refund))
FROM loose JOIN cleared ON cleared.user_id = loose.user_id
WHERE s.user_id = loose.user_id;

WITH loose AS (
  SELECT s.user_id,
         coalesce(sum(coalesce((slot->>'qty')::int, 1) * r.captured_value), 0) AS refund
  FROM public.player_saves AS s
  CROSS JOIN LATERAL jsonb_array_elements(coalesce(s.data->'bank'->'items', '[]'::jsonb)) AS slot
  JOIN v4_retirement AS r ON r.from_id = slot->>'id'
  GROUP BY s.user_id
), cleared AS (
  SELECT s.user_id,
         jsonb_agg(CASE WHEN slot->>'id' IN ('cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate') THEN 'null'::jsonb ELSE slot END
                   ORDER BY ordinality) AS items
  FROM public.player_saves AS s
  CROSS JOIN LATERAL jsonb_array_elements(coalesce(s.data->'bank'->'items', '[]'::jsonb)) WITH ORDINALITY AS t(slot, ordinality)
  WHERE s.user_id IN (SELECT user_id FROM loose)
  GROUP BY s.user_id
)
UPDATE public.player_saves AS s
SET data = jsonb_set(
      jsonb_set(s.data, '{bank,items}', cleared.items),
      '{gold}',
      to_jsonb(coalesce((s.data->>'gold')::bigint, 0) + loose.refund))
FROM loose JOIN cleared ON cleared.user_id = loose.user_id
WHERE s.user_id = loose.user_id;

-- 3. Open listings are relisted as the successor definition, price untouched.
UPDATE public.market_listings AS m
SET item_id = r.to_id,
    content_version = 'v4',
    updated_at = now()
FROM v4_retirement AS r
WHERE m.item_id = r.from_id;

UPDATE public.market_prices AS p
SET item_id = r.to_id,
    content_version = 'v4',
    updated_at = now()
FROM v4_retirement AS r
WHERE p.item_id = r.from_id
  AND NOT EXISTS (
    SELECT 1 FROM public.market_prices AS existing
    WHERE existing.item_id = r.to_id AND existing.plus = p.plus
  );
DELETE FROM public.market_prices AS p
USING v4_retirement AS r
WHERE p.item_id = r.from_id;

-- Only one row may hold status 'active', so v3 retires in the same
-- transaction. Its content, spawn and world rows are all kept intact.
UPDATE public.game_content_versions
SET status = 'retired'
WHERE content_version = 'v3';

UPDATE public.game_content_versions
SET status = 'active'
WHERE content_version = 'v4';

UPDATE public.game_content_control
SET active_content_version = 'v4',
    active_spawn_set_version = 'v4',
    minimum_client_content_version = 'v4',
    manifest_hash = '9608c4031c2bed1b9335802b2328e8b90d7866b5d23110c7d3157fa2f50ebf41',
    activation_timestamp = now(),
    migration_run_id = 'v4-armour-overhaul-20260831'
WHERE singleton;

UPDATE public.game_release_control
SET minimum_client_content_version = 'v4',
    updated_at = now()
WHERE singleton;

DO $v4_activate_exit$
DECLARE
  stragglers integer;
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v4' THEN
    RAISE EXCEPTION 'V4 activation did not take effect';
  END IF;
  IF (SELECT active_spawn_set_version FROM public.game_content_control WHERE singleton) <> 'v4' THEN
    RAISE EXCEPTION 'V4 spawn set activation did not take effect';
  END IF;
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v3') <> 'retired' THEN
    RAISE EXCEPTION 'v3 must be retained as retired for rollback';
  END IF;
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v3') <> 730 THEN
    RAISE EXCEPTION 'v3 rollback data was modified';
  END IF;

  SELECT count(*) INTO stragglers FROM public.player_saves AS s
  WHERE EXISTS (SELECT 1 FROM v4_retirement r WHERE s.data::text LIKE '%"' || r.from_id || '"%');
  IF stragglers <> 0 THEN
    RAISE EXCEPTION '% save(s) still reference a retired armour definition', stragglers;
  END IF;

  SELECT count(*) INTO stragglers FROM public.market_listings AS m
  WHERE m.item_id IN ('cloth_tunic', 'frostguard_plate', 'iron_mail', 'leather_vest', 'linen_robe', 'mithril_plate', 'mystic_robe', 'runite_plate', 'wyrmscale_plate');
  IF stragglers <> 0 THEN
    RAISE EXCEPTION '% market listing(s) still reference a retired armour definition', stragglers;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.player_saves AS s
    WHERE s.data->'armor'->>'id' IS NOT NULL
      AND NOT EXISTS (
        SELECT 1 FROM public.game_content_items i
        WHERE i.content_version = 'v4' AND i.id = s.data->'armor'->>'id')
  ) THEN
    RAISE EXCEPTION 'A save equips an armour definition v4 does not define';
  END IF;

  IF (SELECT count(*) FROM public.game_content_items WHERE content_version = 'v4' AND kind = 'armor') <> 32 THEN
    RAISE EXCEPTION 'V4 must publish exactly 32 armour definitions';
  END IF;
  IF (SELECT count(*) FROM public.game_content_recipes r
      JOIN public.game_content_items i ON i.content_version = r.content_version AND i.id = r.output_item_id
      WHERE r.content_version = 'v4' AND i.kind = 'armor') <> 32 THEN
    RAISE EXCEPTION 'V4 must publish a recipe for every armour definition';
  END IF;
  IF (SELECT maintenance_mode FROM public.game_release_control WHERE singleton) THEN
    RAISE EXCEPTION 'V4 activation must not leave the game in maintenance mode';
  END IF;
END
$v4_activate_exit$;

COMMIT;
