-- V3 consolidation, step 1/3: stage v3 content (inactive).
--
-- GENERATED by scripts/v3/build-migrations.mjs. Do not edit this file directly.
-- Content manifest sha256: f8bc150f0edd4abfdec405dd7f58007d3e9da699100f2ec54cf2ecbd9fa03a0a
-- Generated content SQL sha256: 410a996aca703e0ccb7e7d59d1e4bb0a0835165216ad3d941f5df2bdca6cf771
-- v3 gameplay content is the live v2 content: every content row is copied
-- from v2 inside the database, so no value can drift during the release.
-- v1 and v2 rows are left untouched so rollback stays a control-row update.

BEGIN;

DO $v3_stage_content_guard$
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v2' THEN
    RAISE EXCEPTION 'V3 staging expects v2 to be the active release';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_versions WHERE content_version = 'v3' AND status = 'active') THEN
    RAISE EXCEPTION 'V3 is already active; staging must not run again';
  END IF;
END
$v3_stage_content_guard$;

-- The version row: same player notice and content as v2, new identity/hash.
INSERT INTO public.game_content_versions
  (content_version, spawn_set_version, uuid_namespace, status, manifest_hash, player_notice, starter_loadout, mechanics)
SELECT 'v3', 'v3', uuid_namespace, 'staged', 'f8bc150f0edd4abfdec405dd7f58007d3e9da699100f2ec54cf2ecbd9fa03a0a', player_notice, starter_loadout, mechanics
FROM public.game_content_versions WHERE content_version = 'v2'
ON CONFLICT (content_version) DO UPDATE SET
  spawn_set_version = EXCLUDED.spawn_set_version,
  uuid_namespace = EXCLUDED.uuid_namespace,
  manifest_hash = EXCLUDED.manifest_hash,
  player_notice = EXCLUDED.player_notice,
  starter_loadout = EXCLUDED.starter_loadout,
  mechanics = EXCLUDED.mechanics;

DO $v3_copy_content$
DECLARE
  target text;
  column_list text;
  projection text;
  copied bigint;
  expected bigint;
BEGIN
  FOREACH target IN ARRAY ARRAY['game_content_tiers', 'game_content_items', 'game_content_recipes', 'game_content_recipe_inputs', 'game_content_nodes', 'game_content_monsters', 'game_content_monster_loot', 'game_content_fish', 'game_content_fishing_spots', 'game_content_quests', 'game_content_bosses', 'game_content_migration_rules', 'game_content_progression_levels'] LOOP
    SELECT string_agg(quote_ident(attname), ', ' ORDER BY attnum),
           string_agg(CASE WHEN attname = 'content_version' THEN '''v3'''
                           ELSE quote_ident(attname) END, ', ' ORDER BY attnum)
      INTO column_list, projection
    FROM pg_attribute
    WHERE attrelid = format('public.%I', target)::regclass AND attnum > 0 AND NOT attisdropped;

    EXECUTE format(
      'DELETE FROM public.%I WHERE content_version = %L', target, 'v3');
    EXECUTE format(
      'INSERT INTO public.%I (%s) SELECT %s FROM public.%I WHERE content_version = %L',
      target, column_list, projection, target, 'v2');

    EXECUTE format('SELECT count(*) FROM public.%I WHERE content_version = %L', target, 'v3') INTO copied;
    EXECUTE format('SELECT count(*) FROM public.%I WHERE content_version = %L', target, 'v2') INTO expected;
    IF copied <> expected OR expected = 0 THEN
      RAISE EXCEPTION 'V3 copy of % is incomplete (% of %)', target, copied, expected;
    END IF;
  END LOOP;
END
$v3_copy_content$;

DO $v3_stage_content_exit$
BEGIN
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v3') <> 'staged' THEN
    RAISE EXCEPTION 'V3 content must remain staged after step 1';
  END IF;
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v2' THEN
    RAISE EXCEPTION 'V3 staging changed the active release';
  END IF;
END
$v3_stage_content_exit$;

COMMIT;