-- V4 armour overhaul, step 2/3: stage the v4 world (inactive).
--
-- GENERATED by scripts/v4/build-migrations.mjs. Do not edit this file directly.
-- Stable spawn payload sha256: 67b857de15eb32a8305595f5320fd2b6009e7d6de8bc40c2d53c790a898610cb
-- 369 nodes, 361 monsters, 0 relocated from v3:
-- the armour overhaul changes definitions only, never world geometry.

BEGIN;

DO $v4_stage_world_guard$
BEGIN
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v4') <> 'staged' THEN
    RAISE EXCEPTION 'V4 world staging requires staged v4 content';
  END IF;
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v3' THEN
    RAISE EXCEPTION 'V4 world staging expects v3 to be the active release';
  END IF;
END
$v4_stage_world_guard$;

INSERT INTO public.game_world_spawn_sets
  (content_version, spawn_set_version, source_content_manifest_hash, spawn_hash, model_version,
   cluster_probability, world_width, world_height, movement_speed, path_cell_size,
   winter_geometry, reachability_summary)
SELECT 'v4', 'v4', '9608c4031c2bed1b9335802b2328e8b90d7866b5d23110c7d3157fa2f50ebf41', '67b857de15eb32a8305595f5320fd2b6009e7d6de8bc40c2d53c790a898610cb', model_version,
       cluster_probability, world_width, world_height, movement_speed, path_cell_size,
       winter_geometry, reachability_summary
FROM public.game_world_spawn_sets
WHERE content_version = 'v3' AND spawn_set_version = 'v3'
ON CONFLICT (content_version, spawn_set_version) DO UPDATE SET
  source_content_manifest_hash = EXCLUDED.source_content_manifest_hash,
  spawn_hash = EXCLUDED.spawn_hash;

DELETE FROM public.game_world_nodes WHERE content_version = 'v4';
DELETE FROM public.game_world_monsters WHERE content_version = 'v4';
DELETE FROM public.game_content_spawns WHERE content_version = 'v4';

-- Spawn identities carry forward unchanged; only the UUID namespace input
-- changes (v3:... -> v4:...), exactly as the artifact encodes.
INSERT INTO public.game_content_spawns
  (spawn_id, content_version, spawn_set_version, entity_type, kind, ordinal, active, biome, subzone, x, y)
SELECT extensions.uuid_generate_v5(
         'bf50882c-ad8a-57ab-bb73-3ea3dd8fcb5c'::uuid,
         'v4' || ':' || entity_type || ':' || kind || ':' || ordinal),
       'v4', 'v4', entity_type, kind, ordinal, active, biome, subzone, x, y
FROM public.game_content_spawns
WHERE content_version = 'v3';

INSERT INTO public.game_world_nodes
  (spawn_id, content_version, spawn_set_version, entity_type, kind, cell, biome, subzone, x, y,
   charges, max_charges, gather_s, respawn_s)
SELECT spawn.spawn_id, 'v4', 'v4', 'node', spawn.kind, previous_world.cell, spawn.biome, spawn.subzone,
       spawn.x, spawn.y, definition.max_charges, definition.max_charges, definition.gather_s, definition.respawn_s
FROM public.game_content_spawns AS spawn
JOIN public.game_content_nodes AS definition ON definition.content_version = 'v4' AND definition.kind = spawn.kind
JOIN public.game_content_spawns AS previous ON previous.content_version = 'v3'
  AND previous.entity_type = spawn.entity_type AND previous.kind = spawn.kind AND previous.ordinal = spawn.ordinal
JOIN public.game_world_nodes AS previous_world ON previous_world.spawn_id = previous.spawn_id
WHERE spawn.content_version = 'v4' AND spawn.entity_type = 'node';

INSERT INTO public.game_world_monsters
  (spawn_id, content_version, spawn_set_version, entity_type, kind, cell, biome, subzone, x, y, hp, max_hp, respawn_s)
SELECT spawn.spawn_id, 'v4', 'v4', 'monster', spawn.kind, previous_world.cell, spawn.biome, spawn.subzone,
       spawn.x, spawn.y, definition.hp, definition.hp, definition.respawn_s
FROM public.game_content_spawns AS spawn
JOIN public.game_content_monsters AS definition ON definition.content_version = 'v4' AND definition.kind = spawn.kind
JOIN public.game_content_spawns AS previous ON previous.content_version = 'v3'
  AND previous.entity_type = spawn.entity_type AND previous.kind = spawn.kind AND previous.ordinal = spawn.ordinal
JOIN public.game_world_monsters AS previous_world ON previous_world.spawn_id = previous.spawn_id
WHERE spawn.content_version = 'v4' AND spawn.entity_type = 'monster';

DO $v4_stage_world_exit$
DECLARE
  digest text;
BEGIN
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v4') <> 730 THEN
    RAISE EXCEPTION 'V4 spawn set is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_world_nodes WHERE content_version = 'v4') <> 369 THEN
    RAISE EXCEPTION 'V4 node state is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_world_monsters WHERE content_version = 'v4') <> 361 THEN
    RAISE EXCEPTION 'V4 monster state is incomplete';
  END IF;
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v3') <> 730 THEN
    RAISE EXCEPTION 'V4 staging modified the v3 spawn set';
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || entity_type || ':' || kind || ':' || ordinal || ':' || x::float8::text
             || ':' || y::float8::text || ':' || biome || ':' || subzone, ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_content_spawns WHERE content_version = 'v4';
  IF digest <> '8c6963545a5d7a3c337e51316fa09a08' THEN
    RAISE EXCEPTION 'V4 spawn rows do not match the released artifact (%)', digest;
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || kind || ':' || cell || ':' || x::float8::text || ':' || y::float8::text
             || ':' || max_charges::text || ':' || gather_s::float8::text || ':' || respawn_s::text,
           ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_world_nodes WHERE content_version = 'v4';
  IF digest <> '9e30a2a1ac3633c6cb843a15f7559fbb' THEN
    RAISE EXCEPTION 'V4 world nodes do not match the released artifact (%)', digest;
  END IF;

  SELECT md5(string_agg(
           spawn_id::text || ':' || kind || ':' || cell || ':' || x::float8::text || ':' || y::float8::text
             || ':' || max_hp::text || ':' || respawn_s::text, ',' ORDER BY spawn_id::text))
    INTO digest FROM public.game_world_monsters WHERE content_version = 'v4';
  IF digest <> 'f9a51a13c10411aeee948689ead37a6c' THEN
    RAISE EXCEPTION 'V4 world monsters do not match the released artifact (%)', digest;
  END IF;
END
$v4_stage_world_exit$;

COMMIT;
