-- V7 healing food release, step 3/3: atomically activate v7.
--
-- GENERATED by scripts/v7/build-migrations.mjs. Do not edit this file directly.
-- Content manifest sha256: 89789521c5b84948af1b954e86fdd9d6bea127d8315d3bb5b4f553d340a46935
-- Stable spawn payload sha256: 3c3602f8247d58655d4a004f4af1cf330f606a84d0f22509e8a5ab5cdc47577c
--
-- v6 keeps every content, spawn and world row and is marked 'retired',
-- so release rollback is: retire v7, re-activate v6 and repoint
-- game_content_control.
--
-- No item is deleted, converted, compensated or re-identified, and no player
-- state is touched at all: saves, skills, XP, quests, gold, bank, equipment,
-- inventory, food holdings, market listings, prices and trades are untouched.

BEGIN;

DO $v7_activate_guard$
DECLARE
  issues integer;
  spawn_rows integer;
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v6' THEN
    RAISE EXCEPTION 'V7 activation expects v6 to be the active release';
  END IF;
  SELECT count(*) INTO issues FROM public.game_validate_content_version('v7');
  IF issues <> 0 THEN
    RAISE EXCEPTION 'V7 content failed validation with % issue(s)', issues;
  END IF;
  SELECT count(*) INTO spawn_rows FROM public.game_content_spawns WHERE content_version = 'v7';
  IF spawn_rows <> 730 THEN
    RAISE EXCEPTION 'V7 spawn set is not fully staged';
  END IF;
  IF (SELECT spawn_hash FROM public.game_world_spawn_sets WHERE content_version = 'v7' AND spawn_set_version = 'v7') <> '3c3602f8247d58655d4a004f4af1cf330f606a84d0f22509e8a5ab5cdc47577c' THEN
    RAISE EXCEPTION 'V7 spawn hash does not match the released artifact';
  END IF;
  IF (SELECT manifest_hash FROM public.game_content_versions WHERE content_version = 'v7') <> '89789521c5b84948af1b954e86fdd9d6bea127d8315d3bb5b4f553d340a46935' THEN
    RAISE EXCEPTION 'V7 manifest hash does not match the released artifact';
  END IF;

  -- The food ladder must be exactly the approved 16 stable ids, one per tier,
  -- each active, cooked with Cooking and healing strictly more than the tier below.
  IF (SELECT count(*) FROM public.game_content_items
      WHERE content_version = 'v7' AND kind = 'food' AND active) <> 16 THEN
    RAISE EXCEPTION 'V7 must publish exactly 16 active dishes';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_items
             WHERE content_version = 'v7' AND kind = 'food' AND NOT (id = ANY (ARRAY['ancient_feast', 'ascendant_feast', 'berry_pie', 'fishermans_stew', 'frost_tonic', 'golden_koi_feast', 'hearty_stew', 'honey_bun', 'phoenix_fillet', 'runic_fish_stew', 'shadow_stew', 'starsteel_feast', 'sunspiced_eel', 'void_feast', 'wyrm_feast', 'wyrmforged_feast']::text[]))) THEN
    RAISE EXCEPTION 'V7 publishes a dish outside the approved stable id set';
  END IF;
  IF EXISTS (
    SELECT 1 FROM (
      SELECT heal, level_requirement, tier_index,
             lag(heal) OVER (ORDER BY tier_index) AS previous_heal,
             lag(level_requirement) OVER (ORDER BY tier_index) AS previous_level
      FROM public.game_content_items
      WHERE content_version = 'v7' AND kind = 'food'
    ) AS ladder
    WHERE previous_heal IS NOT NULL AND (heal <= previous_heal OR level_requirement <= previous_level)
  ) THEN
    RAISE EXCEPTION 'V7 food progression is not monotonic';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.game_content_items AS i
    WHERE i.content_version = 'v7' AND i.kind = 'food'
      AND NOT EXISTS (SELECT 1 FROM public.game_content_recipes AS r
                      WHERE r.content_version = i.content_version AND r.output_item_id = i.id AND r.skill = 'cooking')
  ) THEN
    RAISE EXCEPTION 'V7 must publish a Cooking recipe for every dish';
  END IF;

  -- Nothing may be missing from the v7 catalogue that v6 defined.
  IF EXISTS (
    SELECT 1 FROM public.game_content_items AS before
    WHERE before.content_version = 'v6'
      AND NOT EXISTS (SELECT 1 FROM public.game_content_items AS after
                      WHERE after.content_version = 'v7' AND after.id = before.id)
  ) THEN
    RAISE EXCEPTION 'V7 drops an item that v6 defines; the healing release deletes nothing';
  END IF;
  -- Intrinsic values are frozen: this release changes healing only.
  IF EXISTS (
    SELECT 1 FROM public.game_content_items AS before
    JOIN public.game_content_items AS after ON after.content_version = 'v7' AND after.id = before.id
    WHERE before.content_version = 'v6'
      AND (before.name, before.value, before.level_requirement, before.tier_index)
       IS DISTINCT FROM (after.name, after.value, after.level_requirement, after.tier_index)
  ) THEN
    RAISE EXCEPTION 'V7 changes an item name, value, level or tier';
  END IF;
  -- Strength potions are untouched.
  IF EXISTS (
    SELECT 1 FROM public.game_content_items AS before
    JOIN public.game_content_items AS after ON after.content_version = 'v7' AND after.id = before.id
    WHERE before.content_version = 'v6' AND before.kind = 'potion'
      AND (before.strength_pct, before.boost_hits) IS DISTINCT FROM (after.strength_pct, after.boost_hits)
  ) THEN
    RAISE EXCEPTION 'V7 changes a strength potion';
  END IF;
END
$v7_activate_guard$;

-- ---------------------------------------------------------------------------
-- Activation. Only one row may hold status 'active', so v6 retires in
-- the same transaction; its content, spawn and world rows all stay in place.
-- ---------------------------------------------------------------------------
UPDATE public.game_content_versions
SET status = 'retired'
WHERE content_version = 'v6';

UPDATE public.game_content_versions
SET status = 'active'
WHERE content_version = 'v7';

UPDATE public.game_content_control
SET active_content_version = 'v7',
    active_spawn_set_version = 'v7',
    minimum_client_content_version = 'v7',
    manifest_hash = '89789521c5b84948af1b954e86fdd9d6bea127d8315d3bb5b4f553d340a46935',
    activation_timestamp = now(),
    migration_run_id = 'v7-healing-food-release-20260905'
WHERE singleton;

UPDATE public.game_release_control
SET minimum_client_content_version = 'v7',
    updated_at = now()
WHERE singleton;

DO $v7_activate_exit$
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v7' THEN
    RAISE EXCEPTION 'V7 activation did not take effect';
  END IF;
  IF (SELECT active_spawn_set_version FROM public.game_content_control WHERE singleton) <> 'v7' THEN
    RAISE EXCEPTION 'V7 spawn set activation did not take effect';
  END IF;
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v6') <> 'retired' THEN
    RAISE EXCEPTION 'v6 must be retained as retired for rollback';
  END IF;
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v6') <> 730 THEN
    RAISE EXCEPTION 'v6 rollback data was modified';
  END IF;
  IF (SELECT count(*) FROM public.game_content_items WHERE content_version = 'v6') <> 173 THEN
    RAISE EXCEPTION 'v6 rollback catalogue was modified';
  END IF;

  -- Every item reference in every save must resolve against v7.
  IF EXISTS (
    SELECT 1 FROM public.player_saves AS s
    CROSS JOIN LATERAL (
      SELECT s.data->'armor'->>'id' AS id
      UNION ALL SELECT s.data->'weapon'->>'id'
      UNION ALL SELECT s.data->>'food'
      UNION ALL SELECT slot->>'id' FROM jsonb_array_elements(coalesce(s.data->'inv', '[]'::jsonb)) AS slot
      UNION ALL SELECT slot->>'id' FROM jsonb_array_elements(coalesce(s.data->'bank'->'items', '[]'::jsonb)) AS slot
    ) AS ref
    WHERE ref.id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM public.game_content_items i
                      WHERE i.content_version = 'v7' AND i.id = ref.id)
  ) THEN
    RAISE EXCEPTION 'A save references an item definition v7 does not define';
  END IF;

  -- Manual eating must resolve every published dish through the runtime view.
  IF (SELECT count(*) FROM public.game_runtime_items
      WHERE kind = 'food' AND heal > 0 AND id = ANY (ARRAY['ancient_feast', 'ascendant_feast', 'berry_pie', 'fishermans_stew', 'frost_tonic', 'golden_koi_feast', 'hearty_stew', 'honey_bun', 'phoenix_fillet', 'runic_fish_stew', 'shadow_stew', 'starsteel_feast', 'sunspiced_eel', 'void_feast', 'wyrm_feast', 'wyrmforged_feast']::text[])) <> 16 THEN
    RAISE EXCEPTION 'Not every released dish is resolvable by the runtime catalogue';
  END IF;

  IF (SELECT maintenance_mode FROM public.game_release_control WHERE singleton) THEN
    RAISE EXCEPTION 'V7 activation must not leave the game in maintenance mode';
  END IF;
END
$v7_activate_exit$;

COMMIT;
