-- V6 strength potion release, step 3/3: atomically activate v6.
--
-- GENERATED by scripts/v6/build-migrations.mjs. Do not edit this file directly.
-- Content manifest sha256: d87267194b34a7eba300115adfa29600d1d63f52daad4e0e96b947414e673d9e
-- Stable spawn payload sha256: 69a4276f9466c02eef28ff8b8d93804e9d103504c163c1e1aa630dd9aba0c163
--
-- v5 keeps every content, spawn and world row and is marked 'retired',
-- so release rollback is: retire v6, re-activate v5 and repoint
-- game_content_control. The runtime helper still understands the legacy flat
-- buff, so a rollback needs no function restore.
--
-- No item is deleted, converted, compensated or re-identified. Player accounts,
-- saves, skills, XP, progression, quests, gold, bank gold, equipment, inventory,
-- bank, potion holdings, healing food, market sellers, listings, quantities,
-- prices, expiries and trades are all preserved. The only player-state change is
-- the active potion buff, which is converted in place from the v5 flat shape to
-- the v6 percentage shape with its remaining hits intact. Every save that is
-- edited is snapshotted into player_save_backups first.

BEGIN;

DO $v6_activate_guard$
DECLARE
  issues integer;
  spawn_rows integer;
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v5' THEN
    RAISE EXCEPTION 'V6 activation expects v5 to be the active release';
  END IF;
  SELECT count(*) INTO issues FROM public.game_validate_content_version('v6');
  IF issues <> 0 THEN
    RAISE EXCEPTION 'V6 content failed validation with % issue(s)', issues;
  END IF;
  SELECT count(*) INTO spawn_rows FROM public.game_content_spawns WHERE content_version = 'v6';
  IF spawn_rows <> 730 THEN
    RAISE EXCEPTION 'V6 spawn set is not fully staged';
  END IF;
  IF (SELECT spawn_hash FROM public.game_world_spawn_sets WHERE content_version = 'v6' AND spawn_set_version = 'v6') <> '69a4276f9466c02eef28ff8b8d93804e9d103504c163c1e1aa630dd9aba0c163' THEN
    RAISE EXCEPTION 'V6 spawn hash does not match the released artifact';
  END IF;
  IF (SELECT manifest_hash FROM public.game_content_versions WHERE content_version = 'v6') <> 'd87267194b34a7eba300115adfa29600d1d63f52daad4e0e96b947414e673d9e' THEN
    RAISE EXCEPTION 'V6 manifest hash does not match the released artifact';
  END IF;

  -- The potion ladder must be exactly the approved 16 stable ids, one per tier,
  -- each active, craftable with Alchemy and never weaker than the tier below.
  IF (SELECT count(*) FROM public.game_content_items
      WHERE content_version = 'v6' AND kind = 'potion' AND active) <> 16 THEN
    RAISE EXCEPTION 'V6 must publish exactly 16 active potions';
  END IF;
  IF EXISTS (SELECT 1 FROM public.game_content_items
             WHERE content_version = 'v6' AND kind = 'potion' AND NOT (id = ANY (ARRAY['ancient_damage_potion', 'ascendant_damage_potion', 'bronze_damage_potion', 'frostfire_brew', 'froststeel_damage_potion', 'goblins_fury_tonic', 'minor_venom_draught', 'runite_damage_potion', 'serpents_bite_elixir', 'shadow_venom', 'starsteel_damage_potion', 'steel_damage_potion', 'sunsteel_damage_potion', 'voidsteel_damage_potion', 'wyrmforged_damage_potion', 'wyrmsteel_damage_potion']::text[]))) THEN
    RAISE EXCEPTION 'V6 publishes a potion outside the approved stable id set';
  END IF;
  IF EXISTS (
    SELECT 1 FROM (
      SELECT strength_pct, level_requirement, tier_index,
             lag(strength_pct) OVER (ORDER BY tier_index) AS previous_pct,
             lag(level_requirement) OVER (ORDER BY tier_index) AS previous_level
      FROM public.game_content_items
      WHERE content_version = 'v6' AND kind = 'potion'
    ) AS ladder
    WHERE previous_pct IS NOT NULL AND (strength_pct < previous_pct OR level_requirement <= previous_level)
  ) THEN
    RAISE EXCEPTION 'V6 potion progression is not monotonic';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.game_content_items AS i
    WHERE i.content_version = 'v6' AND i.kind = 'potion'
      AND NOT EXISTS (SELECT 1 FROM public.game_content_recipes AS r
                      WHERE r.content_version = i.content_version AND r.output_item_id = i.id AND r.skill = 'alchemy')
  ) THEN
    RAISE EXCEPTION 'V6 must publish an Alchemy recipe for every potion';
  END IF;

  -- Nothing may be missing from the v6 catalogue that v5 defined.
  IF EXISTS (
    SELECT 1 FROM public.game_content_items AS before
    WHERE before.content_version = 'v5'
      AND NOT EXISTS (SELECT 1 FROM public.game_content_items AS after
                      WHERE after.content_version = 'v6' AND after.id = before.id)
  ) THEN
    RAISE EXCEPTION 'V6 drops an item that v5 defines; the potion release deletes nothing';
  END IF;
  -- Healing food must be byte-identical to v5.
  IF EXISTS (
    SELECT 1 FROM public.game_content_items AS before
    JOIN public.game_content_items AS after ON after.content_version = 'v6' AND after.id = before.id
    WHERE before.content_version = 'v5' AND before.kind = 'food'
      AND (before.name, before.heal, before.value, before.level_requirement, before.tier_index)
       IS DISTINCT FROM (after.name, after.heal, after.value, after.level_requirement, after.tier_index)
  ) THEN
    RAISE EXCEPTION 'V6 changes a healing food definition';
  END IF;
END
$v6_activate_guard$;

-- ---------------------------------------------------------------------------
-- Active potion buffs. A valid v5 flat buff is converted by stable potion id to
-- the v6 percentage shape, keeping its remaining hits. Buffs that name an
-- unknown potion, or that are corrupt or exhausted, are cleared. No other save
-- field is touched.
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE v6_buff_saves ON COMMIT DROP AS
SELECT s.user_id, s.rev, s.data AS before_data
FROM public.player_saves AS s
WHERE s.data ? 'buff' AND jsonb_typeof(s.data->'buff') = 'object';

INSERT INTO public.player_save_backups (user_id, rev, data)
SELECT b.user_id, b.rev, b.before_data FROM v6_buff_saves AS b;

-- 1. Convertible buffs: a known, active v6 potion with hits remaining.
UPDATE public.player_saves AS s
SET data = jsonb_set(
      s.data,
      '{buff}',
      jsonb_build_object(
        'strength_pct', potion.strength_pct,
        'hits', (s.data#>>'{buff,hits}')::integer,
        'item', s.data#>>'{buff,item}',
        'content_version', 'v6'
      ),
      true
    )
FROM public.game_content_items AS potion
WHERE potion.content_version = 'v6'
  AND potion.kind = 'potion'
  AND potion.active
  AND potion.id = s.data#>>'{buff,item}'
  AND jsonb_typeof(s.data->'buff') = 'object'
  AND (s.data#>>'{buff,hits}') ~ '^[0-9]+$'
  AND (s.data#>>'{buff,hits}')::integer > 0;

-- 2. Everything else that still looks like a buff is unresolvable: clear it.
UPDATE public.player_saves AS s
SET data = s.data - 'buff'
WHERE s.data ? 'buff'
  AND NOT (
    jsonb_typeof(s.data->'buff') = 'object'
    AND (s.data#>>'{buff,strength_pct}') IS NOT NULL
    AND (s.data#>>'{buff,hits}') ~ '^[0-9]+$'
    AND (s.data#>>'{buff,hits}')::integer > 0
  );

-- ---------------------------------------------------------------------------
-- Activation. Only one row may hold status 'active', so v5 retires in
-- the same transaction; its content, spawn and world rows all stay in place.
-- ---------------------------------------------------------------------------
UPDATE public.game_content_versions
SET status = 'retired'
WHERE content_version = 'v5';

UPDATE public.game_content_versions
SET status = 'active'
WHERE content_version = 'v6';

UPDATE public.game_content_control
SET active_content_version = 'v6',
    active_spawn_set_version = 'v6',
    minimum_client_content_version = 'v6',
    manifest_hash = 'd87267194b34a7eba300115adfa29600d1d63f52daad4e0e96b947414e673d9e',
    activation_timestamp = now(),
    migration_run_id = 'v6-strength-potion-release-20260903'
WHERE singleton;

UPDATE public.game_release_control
SET minimum_client_content_version = 'v6',
    updated_at = now()
WHERE singleton;

-- ---------------------------------------------------------------------------
-- Least-privilege hardening. public.apply_strength_buff is a pure, IMMUTABLE,
-- SECURITY INVOKER helper with SET search_path = public; it is only ever called
-- from inside the authoritative SECURITY DEFINER combat RPCs, which execute as
-- the function owner and therefore keep working. No client role needs, or after
-- this statement has, a direct EXECUTE path to it.
REVOKE ALL
ON FUNCTION public.apply_strength_buff(jsonb, numeric)
FROM PUBLIC, anon, authenticated, service_role;

-- V6 public combat entry points.
--
-- Canonical source for the public SECURITY DEFINER wrappers that V6 corrects.
-- Inlined verbatim into the generated step-3 activation migration by
-- scripts/v6/build-migrations.mjs. Do not hand-patch the emitted SQL.
--
-- Regression fixed here: public.attack_boss asserted the *legacy V1 world
-- contract* (game_assert_action_allowed(true)), so under any non-v1 release —
-- V5 today, V6 after activation — every boss swing from the normal client
-- failed with 'legacy_world_contract_disabled'. The boss fight has no legacy
-- world dependency: attack_boss_v1 reads the authoritative world_boss row and
-- boss_position_at(), not the frozen v1 world tables.
--
-- The gate itself is NOT removed. game_assert_action_allowed(false) still
-- enforces maintenance mode and the minimum client protocol; only the
-- legacy-world-contract branch is switched off, matching every other
-- non-legacy entry point.
--
-- The signature and client contract are unchanged, attack_boss_v1 stays
-- non-public, and this wrapper remains the only client entry point.

CREATE OR REPLACE FUNCTION public.attack_boss(
  _x numeric, _y numeric, _bx numeric, _by numeric, _passive boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.game_assert_action_allowed(false);
  RETURN public.attack_boss_v1(_x, _y, _bx, _by, _passive);
END
$$;

REVOKE ALL ON FUNCTION public.attack_boss(numeric, numeric, numeric, numeric, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.attack_boss(numeric, numeric, numeric, numeric, boolean) TO authenticated;

-- attack_boss_v1 is authoritative and must never be callable by a client role.
REVOKE ALL ON FUNCTION public.attack_boss_v1(numeric, numeric, numeric, numeric, boolean)
FROM PUBLIC, anon, authenticated;




DO $v6_activate_exit$
DECLARE
  converted integer;
  cleared integer;
BEGIN
  IF (SELECT active_content_version FROM public.game_content_control WHERE singleton) <> 'v6' THEN
    RAISE EXCEPTION 'V6 activation did not take effect';
  END IF;
  IF (SELECT active_spawn_set_version FROM public.game_content_control WHERE singleton) <> 'v6' THEN
    RAISE EXCEPTION 'V6 spawn set activation did not take effect';
  END IF;
  IF (SELECT status FROM public.game_content_versions WHERE content_version = 'v5') <> 'retired' THEN
    RAISE EXCEPTION 'v5 must be retained as retired for rollback';
  END IF;
  IF (SELECT count(*) FROM public.game_content_spawns WHERE content_version = 'v5') <> 730 THEN
    RAISE EXCEPTION 'v5 rollback data was modified';
  END IF;
  IF (SELECT count(*) FROM public.game_content_items WHERE content_version = 'v5') <> 173 THEN
    RAISE EXCEPTION 'v5 rollback catalogue was modified';
  END IF;

  -- No save may keep a legacy or malformed buff after conversion.
  IF EXISTS (
    SELECT 1 FROM public.player_saves AS s
    WHERE s.data ? 'buff'
      AND (
        (s.data#>>'{buff,strength_pct}') IS NULL
        OR (s.data#>>'{buff,hits}') !~ '^[0-9]+$'
        OR (s.data#>>'{buff,hits}')::integer <= 0
        OR NOT EXISTS (SELECT 1 FROM public.game_content_items i
                       WHERE i.content_version = 'v6' AND i.kind = 'potion'
                         AND i.active AND i.id = s.data#>>'{buff,item}')
      )
  ) THEN
    RAISE EXCEPTION 'A save still carries an unconverted or unresolvable potion buff';
  END IF;

  -- Every item reference in every save must resolve against v6.
  IF EXISTS (
    SELECT 1 FROM public.player_saves AS s
    CROSS JOIN LATERAL (
      SELECT s.data->'armor'->>'id' AS id
      UNION ALL SELECT s.data->'weapon'->>'id'
      UNION ALL SELECT s.data->>'food'
      UNION ALL SELECT slot->>'id' FROM jsonb_array_elements(coalesce(s.data->'inv', '[]'::jsonb)) AS slot
      UNION ALL SELECT slot->>'id' FROM jsonb_array_elements(coalesce(s.data->'bank'->'items', '[]'::jsonb)) AS slot
    ) AS ref
    WHERE ref.id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM public.game_content_items i
                      WHERE i.content_version = 'v6' AND i.id = ref.id)
  ) THEN
    RAISE EXCEPTION 'A save references an item definition v6 does not define';
  END IF;

  -- Saves still parse into the shape the client contract expects.
  IF EXISTS (
    SELECT 1 FROM public.player_saves AS s
    WHERE jsonb_typeof(s.data->'inv') <> 'array'
       OR jsonb_typeof(s.data->'bank'->'items') <> 'array'
       OR jsonb_typeof(s.data->'skills') <> 'object'
       OR (s.data->'armor') IS NULL
       OR jsonb_typeof(s.data->'armor') NOT IN ('null', 'object')
       OR jsonb_typeof(s.data->'weapon') NOT IN ('null', 'object')
  ) THEN
    RAISE EXCEPTION 'A save no longer matches the expected save shape';
  END IF;

  IF (SELECT maintenance_mode FROM public.game_release_control WHERE singleton) THEN
    RAISE EXCEPTION 'V6 activation must not leave the game in maintenance mode';
  END IF;

  SELECT count(*) INTO converted FROM public.player_saves WHERE data ? 'buff';
  SELECT count(*) INTO cleared FROM v6_buff_saves;
  RAISE NOTICE 'V6 buff conversion: % save(s) inspected, % active buff(s) now on the v6 shape', cleared, converted;
END
$v6_activate_exit$;

COMMIT;